package com.bambuco.salak.model;
// Generated 29/05/2016 10:31:16 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", schema = "public")
public class Module implements java.io.Serializable {

	private int idModule;
	private String name;
	private boolean state;
	private Set<Option> options = new HashSet<Option>(0);

	public Module() {
	}

	public Module(int idModule, String name, boolean state) {
		this.idModule = idModule;
		this.name = name;
		this.state = state;
	}

	public Module(int idModule, String name, boolean state, Set<Option> options) {
		this.idModule = idModule;
		this.name = name;
		this.state = state;
		this.options = options;
	}

	@Id

	@Column(name = "id_module", unique = true, nullable = false)
	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Option> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

}
