package com.bambuco.salak.model;
// Generated 28/05/2016 09:59:11 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Option generated by hbm2java
 */
public class Option implements java.io.Serializable {

	private int idOption;
	private Module module;
	private String name;
	private String value;
	private Boolean state;
	private Set<RoleOption> roleOptions = new HashSet<RoleOption>(0);

	public Option() {
	}

	public Option(int idOption, Module module) {
		this.idOption = idOption;
		this.module = module;
	}

	public Option(int idOption, Module module, String name, String value, Boolean state, Set<RoleOption> roleOptions) {
		this.idOption = idOption;
		this.module = module;
		this.name = name;
		this.value = value;
		this.state = state;
		this.roleOptions = roleOptions;
	}

	public int getIdOption() {
		return this.idOption;
	}

	public void setIdOption(int idOption) {
		this.idOption = idOption;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	public Set<RoleOption> getRoleOptions() {
		return this.roleOptions;
	}

	public void setRoleOptions(Set<RoleOption> roleOptions) {
		this.roleOptions = roleOptions;
	}

}
