package com.bambuco.salak.model;
// Generated 28/05/2016 09:59:11 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ProductTag generated by hbm2java
 */
public class ProductTag implements java.io.Serializable {

	private int idProductTag;
	private Product product;
	private Tag tag;

	public ProductTag() {
	}

	public ProductTag(int idProductTag, Product product, Tag tag) {
		this.idProductTag = idProductTag;
		this.product = product;
		this.tag = tag;
	}

	public int getIdProductTag() {
		return this.idProductTag;
	}

	public void setIdProductTag(int idProductTag) {
		this.idProductTag = idProductTag;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
