package com.bambuco.salak.model;
// Generated 28/05/2016 09:59:11 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * RoleOption generated by hbm2java
 */
public class RoleOption implements java.io.Serializable {

	private int idRoleOption;
	private Option option;
	private Role role;
	private int idRole;

	public RoleOption() {
	}

	public RoleOption(Option option, Role role, int idRole) {
		this.option = option;
		this.role = role;
		this.idRole = idRole;
	}

	public int getIdRoleOption() {
		return this.idRoleOption;
	}

	public void setIdRoleOption(int idRoleOption) {
		this.idRoleOption = idRoleOption;
	}

	public Option getOption() {
		return this.option;
	}

	public void setOption(Option option) {
		this.option = option;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

}
