package com.bambucodev.salak.model;
// Generated 29/05/2016 09:49:36 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductTag generated by hbm2java
 */
@Entity
@Table(name = "product_tag", schema = "public")
public class ProductTag implements java.io.Serializable {

	private int idProductTag;
	private Product product;
	private Tag tag;

	public ProductTag() {
	}

	public ProductTag(int idProductTag, Product product, Tag tag) {
		this.idProductTag = idProductTag;
		this.product = product;
		this.tag = tag;
	}

	@Id

	@Column(name = "id_product_tag", unique = true, nullable = false)
	public int getIdProductTag() {
		return this.idProductTag;
	}

	public void setIdProductTag(int idProductTag) {
		this.idProductTag = idProductTag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tag", nullable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

}
