package com.bambucodev.salak.illusion.dto;
// Generated 29/05/2016 09:49:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.ArrayList;
import java.util.List;

/**
 * Module generated by hbm2java
 */
public class ModuleDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1851486913078641432L;
	private int idModule;
	private String name;
	private boolean state;
	private List<OptionDTO> options = new ArrayList<OptionDTO>(0);

	public ModuleDTO() {
	}

	public ModuleDTO(int idModule, String name, boolean state) {
		this.idModule = idModule;
		this.name = name;
		this.state = state;
	}

	public ModuleDTO(int idModule, String name, boolean state, List<OptionDTO> options) {
		this.idModule = idModule;
		this.name = name;
		this.state = state;
		this.options = options;
	}

	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public List<OptionDTO> getOptions() {
		return this.options;
	}

	public void setOptions(List<OptionDTO> options) {
		this.options = options;
	}

}
