package com.bambucodev.salak.illusion.dto;
// Generated 29/05/2016 09:49:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.ArrayList;
import java.util.List;

/**
 * Option generated by hbm2java
 */
public class OptionDTO implements java.io.Serializable {

	private Long idOption;
	private ModuleDTO module;
	private String name;
	private String value;
	private Boolean state;
	private List<RoleOptionDTO> roleOptions = new ArrayList<RoleOptionDTO>(0);

	public OptionDTO() {
	}

	public OptionDTO(Long idOption, ModuleDTO module) {
		this.idOption = idOption;
		this.module = module;
	}

	public OptionDTO(Long idOption, ModuleDTO module, String name, String value, Boolean state, List<RoleOptionDTO> roleOptions) {
		this.idOption = idOption;
		this.module = module;
		this.name = name;
		this.value = value;
		this.state = state;
		this.roleOptions = roleOptions;
	}

	public Long getIdOption() {
		return this.idOption;
	}

	public void setIdOption(Long idOption) {
		this.idOption = idOption;
	}

	public ModuleDTO getModule() {
		return this.module;
	}

	public void setModule(ModuleDTO module) {
		this.module = module;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	public List<RoleOptionDTO> getRoleOptions() {
		return this.roleOptions;
	}

	public void setRoleOptions(List<RoleOptionDTO> roleOptions) {
		this.roleOptions = roleOptions;
	}

}
