package com.bambuco.salak.illusion.dto;
// Generated 29/05/2016 09:49:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private int idModule;
	private String name;
	private boolean state;
	private Set<Option> options = new HashSet<Option>(0);

	public Module() {
	}

	public Module(int idModule, String name, boolean state) {
		this.idModule = idModule;
		this.name = name;
		this.state = state;
	}

	public Module(int idModule, String name, boolean state, Set<Option> options) {
		this.idModule = idModule;
		this.name = name;
		this.state = state;
		this.options = options;
	}

	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public Set<Option> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

}
