package com.bambuco.salak.illusion.dto;
// Generated 29/05/2016 09:49:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private int idTag;
	private String name;
	private boolean state;
	private Set<ProductTag> productTags = new HashSet<ProductTag>(0);

	public Tag() {
	}

	public Tag(int idTag, String name, boolean state) {
		this.idTag = idTag;
		this.name = name;
		this.state = state;
	}

	public Tag(int idTag, String name, boolean state, Set<ProductTag> productTags) {
		this.idTag = idTag;
		this.name = name;
		this.state = state;
		this.productTags = productTags;
	}

	public int getIdTag() {
		return this.idTag;
	}

	public void setIdTag(int idTag) {
		this.idTag = idTag;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public Set<ProductTag> getProductTags() {
		return this.productTags;
	}

	public void setProductTags(Set<ProductTag> productTags) {
		this.productTags = productTags;
	}

}
